#!/usr/bin/env python3
"""Build data/worlds/cove/zones.json — the cove's water zones for the physics grid.

Zones are polygons in lat/lon:
  cove    the sheltered water inside the Municipal Pier / breakwater / Hyde St Pier
  harbor  the Hyde St harbor basin between the breakwater and Pier 45 / Pier 47
  land    everything south of the coastline (closed through the south edge)
plus `openings` (chords where water exchanges): the Opening, the NE gap, the harbor mouth.

The vertex lists below were hand-selected from the OSM polygons in data/worlds/cove/shoreline.geojson
(local metres about CONFIG.origin) so that zone boundaries run along the structures; the
structures themselves are masked as land first, so slight overlap is harmless.
Re-run after editing: python3 tools/build_zones.py
"""
import json
from _world import KY, kx, world_dir

LAT0, LON0 = 37.8085, -122.4235                       # js/config.js origin
KX = kx(LAT0)
def ll(x, y): return [round(LON0 + x / KX, 6), round(LAT0 + y / KY, 6)]  # GeoJSON order

# --- Municipal Pier inner (cove-side) face, root → tip (from OSM way 82206919) ---
MUNI_INNER = [(-284.5,-38.6),(-276.2,28.4),(-276.9,53.3),(-273.6,87.2),(-266.2,116.3),(-254.0,146.1),
  (-242.5,166.1),(-231.0,182.1),(-213.2,200.9),(-186.2,220.1),(-149.5,234.6),(-127.5,237.9),
  (-113.0,237.5),(-107.8,234.1),(-106.2,229.2),(-105.2,222.7),(-99.7,215.4),(-89.1,211.5),
  (-77.9,214.9),(-71.9,223.1),(-71.1,232.4)]
# --- Breakwater west/south face, Opening end → Jacuzzi (south end) (OSM way 324836244) ---
BW_WEST = [(-15.5,208.8),(-9.5,182.4),(0.0,167.8),(8.4,154.6),(11.9,152.8)]
# --- Breakwater inner (harbor-side) face, east end → Jacuzzi ---
BW_INNER = [(324.2,391.6),(294.8,385.8),(254.4,382.1),(211.9,362.3),(159.2,337.8),(90.5,305.8),
  (18.9,273.2),(1.4,256.0),(-9.7,233.3),(-12.6,208.3),(-6.4,182.6),(8.2,160.1),(11.9,152.8)]
# --- Hyde Street Pier west face, tip → root; east face, tip → root (OSM way 456528981) ---
HYDE_WEST = [(54.4,190.2),(57.7,183.1),(67.9,177.2),(122.8,125.9),(147.1,103.0),(170.0,74.3),(208.0,34.7),(212.1,6.8)]
HYDE_EAST = [(58.5,194.6),(78.1,176.1),(92.9,162.1),(114.9,141.5),(128.0,129.7),(178.8,82.1),(187.3,75.3),
  (198.4,82.4),(213.2,56.4),(222.4,53.1),(226.0,31.9)]
# --- Coast from the Hyde St Pier root west to the Municipal Pier root (OSM way 32648495) ---
COAST_COVE = [(184.4,-27.1),(157.3,-59.6),(115.6,-100.1),(-4.6,-177.5),(-66.3,-198.3),(-103.6,-206.3),
  (-141.0,-191.9),(-177.4,-171.4),(-208.8,-149.2),(-230.6,-128.9),(-247.3,-104.0),(-254.8,-86.4),
  (-259.6,-75.3),(-261.5,-63.5),(-266.0,-36.6)]
# --- Harbor south side: wharf, Pier 47 north face, Pier 45 west/north faces ---
HARBOR_SOUTH = [(312.5,42.2),(313.3,68.6),(388.0,73.8),(406.0,64.8),(450.1,64.0),(456.2,79.1),(481.0,67.5),
  (490.9,58.9),(534.7,74.1),(367.7,209.1),(253.3,311.6),(271.4,333.6),(306.9,310.5),(369.8,274.0),
  (384.3,291.4),(369.0,304.2),(354.0,322.7),(362.4,333.2)]

OPENINGS = [
  {"id": "opening",      "name": "The Opening",  "a": (-71.1,232.4), "b": (-15.5,208.8), "exposed": True,  "zone": "cove"},
  {"id": "ne_gap",       "name": "NE gap",       "a": (11.9,152.8),  "b": (54.4,190.2),  "exposed": False, "zone": "cove"},
  {"id": "harbor_mouth", "name": "Harbor mouth", "a": (324.2,391.6), "b": (362.4,333.2), "exposed": True,  "zone": "harbor"},
]

def ring(pts):
    r = [ll(*p) for p in pts]
    if r[0] != r[-1]: r.append(r[0])
    return r

cove = MUNI_INNER + BW_WEST + HYDE_WEST + COAST_COVE
harbor = [(11.9,152.8)] + HYDE_EAST + HARBOR_SOUTH + BW_INNER

def build_land():
    fc = json.load(open(world_dir("cove") / "shoreline.geojson"))
    ways = [f["geometry"]["coordinates"] for f in fc["features"] if f["properties"]["role"] == "coast"]
    # order east → west, orienting each way to continue the chain
    ways.sort(key=lambda w: -max(c[0] for c in w))
    chain = []
    for w in ways:
        if chain and abs(chain[-1][0] - w[0][0]) > abs(chain[-1][0] - w[-1][0]): w = w[::-1]
        elif not chain and w[0][0] < w[-1][0]: w = w[::-1]
        chain += w
    south = LAT0 - 700 / KY
    ringc = [[chain[0][0], chain[0][1]]] + [[c[0], c[1]] for c in chain] + \
            [[chain[-1][0], south], [chain[0][0], south], [chain[0][0], chain[0][1]]]
    return ringc

zones = {
  "note": "Generated by tools/build_zones.py from OSM geometry; edit that script, not this file.",
  "type": "FeatureCollection",
  "features": [
    {"type": "Feature", "properties": {"zone": "cove"},   "geometry": {"type": "Polygon", "coordinates": [ring(cove)]}},
    {"type": "Feature", "properties": {"zone": "harbor"}, "geometry": {"type": "Polygon", "coordinates": [ring(harbor)]}},
    {"type": "Feature", "properties": {"zone": "land"},   "geometry": {"type": "Polygon", "coordinates": [build_land()]}},
  ],
  "openings": [{"id": o["id"], "name": o["name"], "a": ll(*o["a"]), "b": ll(*o["b"]), "exposed": o["exposed"], "zone": o["zone"]} for o in OPENINGS],
}
out = world_dir("cove") / "zones.json"
out.write_text(json.dumps(zones, separators=(",", ":")))
print("wrote", out, out.stat().st_size, "bytes")
